### ISSUE TITLE
Game crash on deleting last hotbar profile

### ISSUE THREAD

**Issue by vrtkk** [DarkKronicle/RefinedCreativeInventory#2]
all in title
### logs of minecraft
https://gist.github.com/vrtkk/784d719ad34ad25a6a7d22926a5dab07

### Crash logs
https://gist.github.com/vrtkk/161081a03de8e83925cfb20217ea8d8b
https://gist.github.com/vrtkk/3707794fa1dae2be867993f1857ad979
*little clarification if you delete this thing
https://i.imgur.com/eAxNgDm.png

**Comment by DarkKronicle** [comment]
Will be fixed next update
